### PR TITLE
introduce level and scope check

### LINKED ISSUE #5: search goes out of scope
I'm building alternating page headers showing the current chapter on even, and the current section on odd pages. Here is a small example:
```typst
#import "@preview/hydra:0.2.0": hydra

#set heading(numbering: "1.1")
#show heading.where(level: 1): it => pagebreak(weak: true) + it
#set par(justify: true)

#set page(paper: "a7",
  header: locate(loc => {
    if calc.even(loc.page()) {
      hydra(sel: heading.where(level: 1))
    } else {
      [#h(1fr)#hydra(sel: heading.where(level: 2))]
    }
  }),
)

= First chapter
#lorem(10)
== First chapter first section
#lorem(150)
== First chapter second section
#lorem(20)
= Second
#lorem(10)
=== Second chapter first subsection
#lorem(30)
=== Second chapter second subsection
#lorem(40)
```

As you can see, the header on the last page refers to `First chapter first section`; but this is wrong because we're now in `Second chapter`. Are you ok with a PR if I can fix this (make hydra not cross higher-level headings), or do you think waiting for the "new features for general handling of headings" is better?

Second thing, not a bug:
If you have a look at `Second chapter`, what do you think about a `descend-until-level: 3` option? (I felt ridiculous giving `Motivation` and `Outline` full section status :zany_face: )

### PR DESCRIPTION
**Pull request by lkndl**
Fixes #5 . Hope you don't mind?
```rs
prev-eligible
  // and next-eligible // i commented this out
  and ctx.top-margin != none
```
was that important or just a `!= none` check? i don't quite get `fallback-next` yet.
cheerio!

### CODE REVIEW

**Comment by tingerrr** [comment]
As mentioned on #5, I have some tests and a small testing script locally that I wanted to push first. Most importantly, regression tests.

I've taken a short look and the code seems reasonable to me, but quite a bit more complicated than it has to be. The fix I have locally simply adds an after/before bound to the selector in `core.get-adjacent` with a higher level. Especially the extra use of `core.is-redundant` seems problematic, this one should only check if a relevant heading is visible, such that the header would be redundant.

The "testing framework" is written nushell and a bit of python, if you have both of those you could test it yourself after rebasing, otherwise I'll test it locally.

**Comment by tingerrr** [comment]
I was thinking about something like on [this branch](https://github.com/tingerrr/hydra/tree/scoped-search), because it is fairly it doesn't have to be manually set for the easy cases, see the `scoped-search` test reference images, I believe that is what you specified.

**Comment by lkndl** [comment]
nice! But i don't think the `core.is-redundant` was so far off. The test case below ([adapted](https://github.com/tingerrr/hydra/blob/scoped-search/tests/typ/scoped-search/test.typ) with everything below `= Second` a bit different) fails on page 7 with a redundant header referencing section `2.2` right above the new chapter heading `3 Third`.
```rs
= First chapter
#lorem(10)
== First chapter first section
#lorem(150)
== First chapter second section
#lorem(20)
= Second
#lorem(30)
== Second section zero
=== Second subsection one
#lorem(90)
== Second section one
#lorem(25)
= Third
#lorem(20)
== Third section one
#lorem(180)
= Fourth
#lorem(200)
```

grafik

**Comment by tingerrr** [comment]
That's true, the redundancy has to check for this too. It seems that this complicates the API more than I hoped though, the next heading should use a different selector to account for its own and higher levels. Maybe I do away with selectors in general, they only seem to cause trouble here.

**Comment by tingerrr** [comment]
So I've been working `v0.3.0` since #5 was opened, and the internal API has changed quite a bit by now. It's already fixed on that branch, so I'll close this. Thank you for putting in the work and for taking the time to test my branch to iron out issues with the implementation!

**Pull request closed without merging**
