### PR TITLE
Filter candidates defined after the current page

### PR DESCRIPTION
**Pull request by freundTech**
Previously when both prev and last candidates were none hydra would show candidates defined on later pages. I believe that candidates defined on pages after the current page should never be displayed.

### CODE REVIEW

**Comment by freundTech** [comment]
Or should this be configurable?
I personally can't think of any option why one would want to display a heading defined on a later page.
You basically already signed off on this in https://github.com/tingerrr/hydra/pull/19#discussion_r1659648664, but through the restructuring of that PR it was changed to only affect `last` candidates, which I think was a mistake.

**Comment by tingerrr** [comment]
Unfortunate that it slipped through my review, thank you! Could you update the changelog to reflect that fix with a link to the PR (i.e. `#21`)?

**Comment by freundTech** [comment]
Done!

**Comment by tingerrr** [comment]
Thank you!

**Pull request merged**
